### PR TITLE
update hardcore to amsterdam/tnm24 version

### PR DESCRIPTION
**Pull request by Janna112358**
### Hardcore break update

At TNM 24, we had a workshop to discuss some variants of the hardcore break. We decided to introduce this "Amsterdam" version (which in turn was inspired by Lille's version) to everyone. I believe it really caught on - with everyone playing this version at the TNM. So, I would propose we update it in the player and sheets (will make a PR for that also). 

Alternatively, we could also add it as a new special break. IMO both versions are so similar that it's not very helpful to have two versions "alive" at the same time, so I opted to replace it for now.

### Technical

- I updated and tested (with local server) the notes of the hardcore break in defaultTunes.ts
- I removed the "VolumeHack". I don't think this version of the break needs a change in volume - and I also couldn't hear any volume changes in the original one. But maybe this is needed or it does something else? I'm not sure, happy to learn!

### Spelling?

Should it be hardcore (the music genre) instead of hard core (like the core of a group)?

### CODE REVIEW

**Comment by cdauth** [comment]
The code itself looks good. It makes sense to remove the volume hack for the new notation. In the old one it was needed, but it doesn't seem to be working (also in Karla Break). I've opened #63 for this.

To change the name of an existing break, the `displayName` property should be used so that the break will keep working in existing songs that are stored on people’s devices. So `'Hard Core Break': {` should stay, but an additional `displayName: 'Hardcore Break'` should be specified.

I agree that the Amsterdam notation seems to be more popular now, so I think it's fine to change the notes in the player and in the tune sheets. However, I personally really like the old version, so I'm wondering whether we can keep it in the player as a variety? The question would be how to call it. “Hardcore Break (St. Petersburg)”? I don’t really know which band introduced the current notation.

**Comment by Janna112358** [comment]
Thanks! Added the displayname

I don't know the origins of the current version either... Maybe a generic name like "hardcore break (original)"? 
We could also keep the key "Hard Core Break" for the current version with displayname "Hardcore Break (original)" so as not to change people's songs at all. Then the new one can have key "Hardcore Break".

**Comment by Janna112358** [comment]
I've updated as described above so it's ready in principal. Happy to update to a clearer name than "Hardcore break (original)" for the current version.

**Comment by cdauth** [comment]
I have fixed the volume hack now.

Your code looks good to merge, just one cosmetic detail: The new Hardcore Break doesn't need the `displayName` property, as it's the same as the pattern name.

**Comment by Janna112358** [comment]
Done!

**Review by cdauth — APPROVED** [review]

**Pull request merged**
